name: Build and deploy to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch: {}

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: |
          rm -rf node_modules package-lock.json
          npm install

      - name: Rebuild native modules
        run: npm rebuild

      - name: Build project
        run: npm run build

      - name: Move build to docs folder
        run: |
          rm -rf docs
          mv dist docs

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v4

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
