name: Build and deploy to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch: {}

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Clean docs folder
        run: |
          find docs -type l -delete
          find docs -name ".DS_Store" -delete
          find docs -name ".vite*" -exec rm -rf {} +
          find docs -name ".cache" -exec rm -rf {} +

      - name: Fix permissions and package artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: docs

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          artifact_name: github-pages
